### PR TITLE
UI_ES.txt - Patch 1.1 hotfix 

### PR DESCRIPTION
**Pull request by JhonArroyo**
I removed the accents to better suit the type of **encoding** you gave the .txt file to avoid so-called **_hieroglyph_**.
Also review a **specific phrase** and take it to a more **neutral** Spanish.

### CODE REVIEW

**Comment by ChuckTheSheep** [comment]
What type of encoding would better suite the accents? My computer generates UTF-8.

**Comment by JhonArroyo** [comment]
I'm going to try the .txt if it doesn't give me those hieroglyphics, there may be a problem when encoding the accents.

**Comment by JhonArroyo** [comment]
I just finished testing and the only way the hieroglyphs didn't appear to me was by removing the accents, I even tried to reverse-encode those accents but it didn't work. 

List of accents in spanish:
Ñ = Ã‘
ñ = Ã±
á = Ã¡
é = Ã©
í = Ã*
ó = Ã³
ú = Ãº
Á = Ã
É = Ã‰
Í = Ã
Ó = Ã“
Ú = Ãš

**Comment by JhonArroyo** [comment]
Checking the folder of translations of my language made by the **PZ developers** I noticed that they encode in **ANS**I so I changed the encoding, tried it and each accent worked. so the pull request I made is **not necessary**. In conclusion just change the encoding UI_ES.txt (**UTF-8**) to (**ANSI**).

**Comment by ChuckTheSheep** [comment]
Will do, thanks!

**Comment by JhonArroyo** [comment]
you welcome

**Comment by ChuckTheSheep** [comment]
I re-encoded it to Windows-1252 as recommended from a website - it appears as ASNI on my end. Let me know if the accents/special characters are still giving you issues.

**Comment by JhonArroyo** [comment]
I wanted to tell you about that before but I was busy, and it's practically the same (Windows-1252 - ANSI) so it's more convenient to use the one you investigated. I just tried it and there're no more problems with accents.

**Comment by ChuckTheSheep** [comment]
Nice, thanks for confirming it!

**Pull request closed without merging**
